//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        public int ID { get; set; }
        public string DESCRIPTION { get; set; }
        public decimal PRICE { get; set; }

        //public PRODUCT(int iD, string dESCRIPTION, decimal pRICE)
        //{
        //    this.ID = iD;
        //    this.DESCRIPTION = dESCRIPTION;
        //    this.PRICE = pRICE;
        //}
    }
}
